const path = require("path");

module.exports = (env) => {
  return {
    mode: env.production ? "production" : "development",
    // Source file we have written
    entry: "./src/js/index.js",
    output: {
      // File that will be generated by Webpack
      filename: "main.js",
      path: path.resolve(__dirname, "dist"),
    },
    module: {
      rules: [
        {
          // Used to transpile JS files
          test: /\.m?js$/,
          exclude: /(node_modules)/,
          use: {
            loader: "babel-loader",
            options: {
              presets: ["@babel/preset-env"],
            },
          },
        },
      ],
    },
    // Webpack Server: run "start" script to start server
    devServer: {
      static: {
        directory: path.join(__dirname, "dist"),
      },
      compress: true,
      port: 8080,
    },
  };
};
